<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_4</name>
   <tag></tag>
   <elementGuidId>d1f29ec8-adc7-435b-b1f7-ccdf3d2ca9d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat datang, Admin PeTIK'])[1]/following::h3[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;4&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>9e9c9fa1-744d-447b-911e-dc9b3d8ce7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold mb-0</value>
      <webElementGuid>4bebc066-15d8-4b4f-a6b2-d295396effb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3dbe853c-7d46-40d6-9370-7f6dec6117a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;row g-4 mb-4&quot;]/div[@class=&quot;col-sm-6 col-xl-3&quot;]/div[@class=&quot;card stat-card p-4&quot;]/div[@class=&quot;d-flex justify-content-between align-items-center&quot;]/div[1]/h3[@class=&quot;fw-bold mb-0&quot;]</value>
      <webElementGuid>a77dd968-d57e-43c0-bed6-02ad299ed93a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat datang, Admin PeTIK'])[1]/following::h3[3]</value>
      <webElementGuid>3b1ed586-487c-4f85-90eb-d96bee1b225e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard Admin'])[1]/following::h3[3]</value>
      <webElementGuid>a24dc6a8-bd2a-46c2-9679-ce7a7e5431d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Sistem'])[1]/preceding::h3[2]</value>
      <webElementGuid>e3c43d33-fe83-4fce-802e-5a139a857ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4']/parent::*</value>
      <webElementGuid>82dc7c34-e945-4a73-92f8-1cf59417dceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/h3</value>
      <webElementGuid>8dd584a3-b002-4be8-8df6-097148512919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = '4' or . = '4')]</value>
      <webElementGuid>cafd5b5f-d441-42c0-9a56-7d007e5cd293</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
