<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>6d0f865a-e4d2-4c4f-9f58-e51de560eb48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Pertemuan 1'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-outline-primary.w-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Download&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>697afbb4-ef24-4084-8838-c7bcf3ca9a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/storage/materials/s5PPo9PceIRj3oE5O0DCKNKCueXppHHCGn8TwtpD.doc</value>
      <webElementGuid>8885c0f1-1518-42fa-a29a-abb78a3ca788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e0ec71a4-b79d-4b1e-8c2c-54e429c889b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-outline-primary w-100</value>
      <webElementGuid>a8db909b-2b7b-4bbe-896b-5440dc3fb0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                         Download
                                    </value>
      <webElementGuid>ee207629-bca1-45a7-a721-144ad22df933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;mb-4&quot;]/div[@class=&quot;row g-3&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;card p-3 h-100 d-flex flex-column justify-content-between&quot;]/div[@class=&quot;mt-2&quot;]/a[@class=&quot;btn btn-sm btn-outline-primary w-100&quot;]</value>
      <webElementGuid>1f5edf2f-4cef-4ea4-8c7e-5b2103f25303</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pertemuan 1'])[1]/following::a[1]</value>
      <webElementGuid>19527fba-04b0-42bd-bb2a-db7970815831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengenalan Web Desain'])[1]/following::a[1]</value>
      <webElementGuid>95ad4869-48a9-442a-b6a9-a2f1a9d59043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>46f1cc7f-fa47-4c0e-85b0-b20031e753f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/storage/materials/s5PPo9PceIRj3oE5O0DCKNKCueXppHHCGn8TwtpD.doc']</value>
      <webElementGuid>9e961b1c-6096-4f0b-bfc7-d2fabf1a5f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>bd0ba49f-def8-4500-a495-81b333384f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/storage/materials/s5PPo9PceIRj3oE5O0DCKNKCueXppHHCGn8TwtpD.doc' and (text() = '
                                         Download
                                    ' or . = '
                                         Download
                                    ')]</value>
      <webElementGuid>3c11bb09-0163-44a7-bbc8-5e4d13d015c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
