<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_bi bi-list fs-4</name>
   <tag></tag>
   <elementGuidId>9a612fe0-a56a-497b-a938-808e34e4c873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnToggleSidebar']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-list.fs-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0cdd7347-f217-441b-aef5-cb9c72394835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-list fs-4</value>
      <webElementGuid>51777aaa-fc74-40cf-9b19-b6016d6e66ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnToggleSidebar&quot;)/i[@class=&quot;bi bi-list fs-4&quot;]</value>
      <webElementGuid>f0a8a18d-4c4a-4852-992d-6246ae75dca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btnToggleSidebar']/i</value>
      <webElementGuid>4ad38213-f118-47d9-a9b4-46b5c9d5d554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/i</value>
      <webElementGuid>c5f77ff2-8bde-4cef-a620-9483641a53ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
