<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Logout_bi bi-list fs-4</name>
   <tag></tag>
   <elementGuidId>dd28910a-f5c8-4fb3-a5ec-3896c8f91f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSidebarToggle']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-list.fs-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ee4471e9-39ed-40b9-95be-32c70cecc1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-list fs-4</value>
      <webElementGuid>f53edc29-a02b-4802-acef-7ea7e61560bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSidebarToggle&quot;)/i[@class=&quot;bi bi-list fs-4&quot;]</value>
      <webElementGuid>2c7455c2-24b0-43fa-b3b7-df1740e5125e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btnSidebarToggle']/i</value>
      <webElementGuid>0d291626-0a94-4e26-b7fb-3fa44ff8251d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/i</value>
      <webElementGuid>82f1ad0d-b72c-40c1-b0e9-ec1856303fd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
