<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jadwal Mengajar</name>
   <tag></tag>
   <elementGuidId>b8af4ea5-e6b3-408b-a76e-a290065813b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebarMenu']/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Jadwal Mengajar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a21a5c5-7b3e-480e-8cbd-b05b0d8a0b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/lecturer/schedules</value>
      <webElementGuid>72aef32b-8154-434f-a50a-7521a8d522b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>3b78ef76-6f5b-4d5d-8d35-163f31355474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                     Jadwal Mengajar
                </value>
      <webElementGuid>cc123a06-214b-4c9f-9cb2-6df68cc904b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarMenu&quot;)/ul[@class=&quot;nav flex-column gap-1&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]</value>
      <webElementGuid>b61a6cff-5280-4528-86a8-d58f72eb2c82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarMenu']/ul/li[2]/a</value>
      <webElementGuid>215fc78f-515d-4796-9054-f08e24cdfd65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PeTIK Jombang'])[1]/following::a[2]</value>
      <webElementGuid>461c720e-6418-4d55-8c0c-ffb54eabf27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jadwal Mengajar']/parent::*</value>
      <webElementGuid>3667af69-4004-4f89-a436-c3660798ddc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/lecturer/schedules']</value>
      <webElementGuid>e91856d0-fa2b-4114-ad11-2f428e05ced9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>bc4545fd-f22f-49b2-869f-40482c16bccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/lecturer/schedules' and (text() = '
                     Jadwal Mengajar
                ' or . = '
                     Jadwal Mengajar
                ')]</value>
      <webElementGuid>686aaecc-4649-44ad-ab50-64afec524112</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
