<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih Semester --                _8aa67a</name>
   <tag></tag>
   <elementGuidId>1624b141-a29a-4960-870f-6a02f297ddb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='semester']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;semester&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;semester&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ce32598d-5662-4c97-8389-38c60dc1ba9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>semester</value>
      <webElementGuid>20056981-8471-4b38-8b38-8a12b8652b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>1c5c4c51-3aff-415a-a0f2-b610665f1bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            -- Pilih Semester --
                                                            Semester
                                    1
                                                            Semester
                                    2
                                                            Semester
                                    3
                                                            Semester
                                    4
                                                            Semester
                                    5
                                                            Semester
                                    6
                                                            Semester
                                    7
                                                            Semester
                                    8
                                                    </value>
      <webElementGuid>507c58a7-43e9-4c77-861b-d428ab00e98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-content&quot;]/div[@class=&quot;card p-4 shadow-sm&quot;]/form[1]/div[@class=&quot;row g-3&quot;]/div[@class=&quot;col-md-6&quot;]/select[@class=&quot;form-select&quot;]</value>
      <webElementGuid>84a48f44-0a74-4625-b7dc-dca11a4687a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='semester']</value>
      <webElementGuid>a3d71129-4f9e-49c7-aea3-ad727e1efc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>41e607ce-40ef-4ca3-bc66-2484812abb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi'])[1]/preceding::select[1]</value>
      <webElementGuid>b777de8b-0a8e-487a-8a3a-a4f39eb329ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>10277f26-cc5b-4567-9d10-ed85efcc196c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>e7299e7b-32f7-4eb4-a29e-04ef5b021e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'semester' and (text() = '
                            -- Pilih Semester --
                                                            Semester
                                    1
                                                            Semester
                                    2
                                                            Semester
                                    3
                                                            Semester
                                    4
                                                            Semester
                                    5
                                                            Semester
                                    6
                                                            Semester
                                    7
                                                            Semester
                                    8
                                                    ' or . = '
                            -- Pilih Semester --
                                                            Semester
                                    1
                                                            Semester
                                    2
                                                            Semester
                                    3
                                                            Semester
                                    4
                                                            Semester
                                    5
                                                            Semester
                                    6
                                                            Semester
                                    7
                                                            Semester
                                    8
                                                    ')]</value>
      <webElementGuid>4a4fa3ae-fa53-4dd0-9de8-7003382a88da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
