<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>334c963e-6845-4195-b864-2a00426c06a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nav-btn-login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Masuk&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db5173f6-3acf-44c4-a46d-5c72ecdb08bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/login</value>
      <webElementGuid>aca37776-ace3-47e7-8a22-a6e1a2cb0c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-btn-login</value>
      <webElementGuid>2368ca96-d638-4561-8515-e1019490e3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 Masuk
                            </value>
      <webElementGuid>f928a546-a38d-43b2-bec8-8f14c999f304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/nav[@class=&quot;navbar&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;d-flex justify-content-between align-items-center w-100&quot;]/div[@class=&quot;d-flex align-items-center gap-3&quot;]/a[@class=&quot;nav-btn-login&quot;]</value>
      <webElementGuid>ee3a8550-8cf3-4b3e-986a-7a779afb7bc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>ff81478d-919a-436b-b05d-d4098c583709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/login']</value>
      <webElementGuid>39baf19f-2fcd-4cde-a988-02ff15c9f9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>c9412d34-7858-489c-99bd-fd5c9c2812d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/login' and (text() = '
                                 Masuk
                            ' or . = '
                                 Masuk
                            ')]</value>
      <webElementGuid>c8d3ada6-65bb-4eb2-aa14-0d12806f037b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
