<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Muhammad Miftahul Huda_grades2assignment</name>
   <tag></tag>
   <elementGuidId>9426f569-25a6-4fb6-9105-71466859b035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='grades[2][assignment]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;grades[2][assignment]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;grades\[2\]\[assignment\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ccb8c8c7-9cf3-45be-ba13-fcfcdf16c871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e34af1db-e693-461c-82c3-b5e4ad09892a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>grades[2][assignment]</value>
      <webElementGuid>b6565589-872b-4981-9557-9b862ea9740c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm grade-input assignment-input</value>
      <webElementGuid>b6f3249a-6d1c-4ccb-a9f8-c8e883e850bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-student</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7335a470-9100-4229-9eeb-f55f43cc3039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>275ab0ce-8234-4d1f-a623-928ecff2de0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>f72422b9-8132-4a5f-aa5d-663f1b8389b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>8d58b3fc-9025-466f-883b-0dbf1b4b00a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3721d028-5f9f-4367-8cc9-1b9796073978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-content&quot;]/form[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body p-0&quot;]/table[@class=&quot;table table-hover mb-0&quot;]/tbody[1]/tr[2]/td[@class=&quot;text-center&quot;]/input[@class=&quot;form-control form-control-sm grade-input assignment-input&quot;]</value>
      <webElementGuid>b97902da-7f56-445c-8ce9-5b82f020f9ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='grades[2][assignment]']</value>
      <webElementGuid>1d38c862-c3ce-4008-bfac-fa10e4845aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>d3fd2ea3-25fe-439e-b604-3c1aeb3a7ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'grades[2][assignment]' and @placeholder = '0']</value>
      <webElementGuid>53e80243-7c7b-4273-8c2a-4a44d94cef11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
