<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Muhammad Miftahul Huda_grades2final_exam</name>
   <tag></tag>
   <elementGuidId>1ad9db09-2dae-459d-87a7-73110a31e760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='grades[2][final_exam]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;grades[2][final_exam]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;grades\[2\]\[final_exam\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35779f97-c545-4325-b8ac-22e2634050da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>90071185-10a9-46e9-8a56-e0558351d980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>grades[2][final_exam]</value>
      <webElementGuid>8b940aa4-46ff-491b-a8ea-8dee9201cace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm grade-input final-input</value>
      <webElementGuid>435bb5af-a242-471b-b65e-12b53644e297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-student</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>060ff0fb-e192-411a-aafd-e01673f89b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af76ef19-5088-43f7-94cc-c0c3f7386bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>68c1beda-c32b-4ba3-85cb-48a4c0f4b6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>74400a88-1bff-4293-a15e-5c54e0348635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b6e9a8e9-0770-47d7-9576-2d9771dc3376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-content&quot;]/form[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body p-0&quot;]/table[@class=&quot;table table-hover mb-0&quot;]/tbody[1]/tr[2]/td[@class=&quot;text-center&quot;]/input[@class=&quot;form-control form-control-sm grade-input final-input&quot;]</value>
      <webElementGuid>3c53b778-3d0b-4de9-acd9-e55f40fc2a04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='grades[2][final_exam]']</value>
      <webElementGuid>666612eb-1131-49b7-aadb-47a940cf7950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/input</value>
      <webElementGuid>7aef6925-2ac9-4ef2-998b-4bcac9028ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'grades[2][final_exam]' and @placeholder = '0']</value>
      <webElementGuid>dcdaaf6e-42f5-41da-b441-2218156c5a7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
