<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fardhan Maulana Yunandar_grades1assignment</name>
   <tag></tag>
   <elementGuidId>4c5eb751-7c0b-453a-9c83-caa49aaa20e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='grades[1][assignment]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;grades[1][assignment]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;grades\[1\]\[assignment\]&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d8f49ed-5f6d-40dc-837c-dd36b5a708a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>905962c5-532e-49d6-8879-128e446ceaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>grades[1][assignment]</value>
      <webElementGuid>fe3828ca-f037-4701-815e-9d067d76b652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm grade-input assignment-input</value>
      <webElementGuid>b6c7eb1e-0568-4b43-a2b6-9d84cefcb2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-student</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ecf54c06-8374-4cf4-adc8-ff422cbc6121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>95931404-36fc-48d2-9a08-144bdcb2b0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e369edab-cdc4-4240-9bf3-d0778a965884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>c9dd6976-d13f-40f3-b94a-5d6de9920cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e9357cfc-6c0a-4cfe-bc81-7a3a90186636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-content&quot;]/form[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body p-0&quot;]/table[@class=&quot;table table-hover mb-0&quot;]/tbody[1]/tr[1]/td[@class=&quot;text-center&quot;]/input[@class=&quot;form-control form-control-sm grade-input assignment-input&quot;]</value>
      <webElementGuid>275c9cee-e633-4719-a6f0-07e3612be776</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='grades[1][assignment]']</value>
      <webElementGuid>c3d41d33-1cb1-43d8-91b7-fe2a0167164b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>0b2805c7-99a0-4658-a7bd-f0d446fe91c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'grades[1][assignment]' and @placeholder = '0']</value>
      <webElementGuid>1d90e9c7-f418-4e5e-85fb-7a2f47485506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
